# Generated by Django 2.2.12 on 2020-05-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
        ('profiles', '0002_analyst_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyst',
            name='websites',
            field=models.ManyToManyField(null=True, to='websites.Website'),
        ),
    ]
