# Generated by Django 2.2.12 on 2020-05-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='status',
            field=models.CharField(blank=True, choices=[('URL VERIFIED', 'URL VERIFIED'), ('SCRIPT VERIFIED', 'SCRIPT VERIFIED')], default='URL VERIFIED', max_length=256, null=True),
        ),
    ]
