# Generated by Django 2.2.12 on 2020-05-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_website_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='apikey',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Website apikey'),
        ),
    ]
